In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt

%matplotlib inline

In [7]:
df1 = pd.read_csv('/Users/obo/Downloads/archive/attendance.csv')
df1.head()

      team  team_name  year   total    home    away  week  weekly_attendance
0  Arizona  Cardinals  2000  893926  387475  506451     1            77434.0
1  Arizona  Cardinals  2000  893926  387475  506451     2            66009.0
2  Arizona  Cardinals  2000  893926  387475  506451     3                NaN
3  Arizona  Cardinals  2000  893926  387475  506451     4            71801.0
4  Arizona  Cardinals  2000  893926  387475  506451     5            66985.0

In [8]:
df1.describe()

,year,total,home,away,week,weekly_attendance
count,10846.000000,1.084600e+04,10846.000000,10846.000000,10846.000000,10208.000000
mean,2009.528213,1.080910e+06,540455.012539,540455.012539,9.000000,67556.876567
std,5.753415,7.287697e+04,66774.652550,25509.325673,4.899205,9022.015325
min,2000.000000,7.606440e+05,202687.000000,450295.000000,1.000000,23127.000000
25%,2005.000000,1.040509e+06,504360.000000,524974.000000,5.000000,63245.500000
50%,2010.000000,1.081090e+06,543185.000000,541757.000000,9.000000,68334.000000
75%,2015.000000,1.123230e+06,578342.000000,557741.000000,13.000000,72544.750000
max,2019.000000,1.322087e+06,741775.000000,601655.000000,17.000000,105121.000000

In [9]:
df1.corr(numeric_only= True)

,year,total,home,away,week,weekly_attendance
year,1.000000e+00,9.102331e-02,4.967082e-02,1.300211e-01,8.732970e-16,0.045954
total,9.102331e-02,1.000000e+00,9.369662e-01,4.042202e-01,3.513003e-17,0.504857
home,4.967082e-02,9.369662e-01,1.000000e+00,5.913944e-02,7.449069e-19,0.473034
away,1.300211e-01,4.042202e-01,5.913944e-02,1.000000e+00,7.238674e-17,0.204073
week,8.732970e-16,3.513003e-17,7.449069e-19,7.238674e-17,1.000000e+00,-0.039609
weekly_attendance,4.595372e-02,5.048566e-01,4.730336e-01,2.040732e-01,-3.960883e-02,1.000000

In [10]:
df2 = pd.read_csv('/Users/obo/Downloads/archive/games.csv')
df2.head()

,year,week,home_team,away_team,winner,tie,day,date,time,pts_win,pts_loss,yds_win,turnovers_win,yds_loss,turnovers_loss,home_team_name,home_team_city,away_team_name,away_team_city
0,2000,1,Minnesota Vikings,Chicago Bears,Minnesota Vikings,NaN,Sun,September 3,1:00PM,30,27,374,1,425,1,Vikings,Minnesota,Bears,Chicago
1,2000,1,Kansas City Chiefs,Indianapolis Colts,Indianapolis Colts,NaN,Sun,September 3,1:00PM,27,14,386,2,280,1,Chiefs,Kansas City,Colts,Indianapolis
2,2000,1,Washington Redskins,Carolina Panthers,Washington Redskins,NaN,Sun,September 3,1:01PM,20,17,396,0,236,1,Redskins,Washington,Panthers,Carolina
3,2000,1,Atlanta Falcons,San Francisco 49ers,Atlanta Falcons,NaN,Sun,September 3,1:02PM,36,28,359,1,339,1,Falcons,Atlanta,49ers,San Francisco
4,2000,1,Pittsburgh Steelers,Baltimore Ravens,Baltimore Ravens,NaN,Sun,September 3,1:02PM,16,0,336,0,223,1,Steelers,Pittsburgh,Ravens,Baltimore

In [11]:
df3 = pd.read_csv('/Users/obo/Downloads/archive/standings.csv')
df3.head()

,team,team_name,year,wins,loss,points_for,points_against,points_differential,margin_of_victory,strength_of_schedule,simple_rating,offensive_ranking,defensive_ranking,playoffs,sb_winner
0,Miami,Dolphins,2000,11,5,323,226,97,6.1,1.0,7.1,0.0,7.1,Playoffs,No Superbowl
1,Indianapolis,Colts,2000,10,6,429,326,103,6.4,1.5,7.9,7.1,0.8,Playoffs,No Superbowl
2,New York,Jets,2000,9,7,321,321,0,0.0,3.5,3.5,1.4,2.2,No Playoffs,No Superbowl
3,Buffalo,Bills,2000,8,8,315,350,-35,-2.2,2.2,0.0,0.5,-0.5,No Playoffs,No Superbowl
4,New England,Patriots,2000,5,11,276,338,-62,-3.9,1.4,-2.5,-2.7,0.2,No Playoffs,No Superbowl

In [ ]:
plt.figure(figsize=(10, 6))
plt.bar(best_intermediate.Title, best_intermediate.Rating, color='green', label ='Top 5')
plt.bar(worst_intermediate.Title, worst_intermediate.Rating, color='red', label ='Bottom 5')
plt.xlabel('Exercise and Ranking')
plt.ylabel('Rating')
plt.xticks(rotation=45)
plt.title('Top 5 and Bottom 5 Intermediate Exercises')
plt.legend()